# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "03-solution-modules" ]
  pull_request:
    branches: [ "main", "03-solution-modules" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: csharpier check
      run: |
          dotnet tool restore
          dotnet csharpier --check .
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run Stryker Mutator
      run: |
          cd UnitTests/
          dotnet tool restore
          dotnet stryker
